import 'keys.dart';

Map<String, String> ar = {
  appName: 'يمن عروض',

  //onboarding
  lblOnboardingMap: 'اكتشف العروض القريبة منك',
  lblOnboardingYO: 'عروض تناسب ذوقك',
  lblOnboardingFav: 'تابع متاجرك واحفظ اللي يعجبك',
  txtOnboardingMap:
      'بدون تعب ولا دوار، شوف أقرب العروض من حولك بكل سهولة، ووفّر وقتك وفلوسك.',
  txtOnboardingYO:
      'نختار لك العروض اللي تهمك، حسب اللي يعجبك وتشوفه بالتطبيق، علشان تلاقي كل جديد بسرعة.',
  txtOnboardingFav:
      'ما يفوتك شي! احفظ العروض اللي تحبها، وخليك أوّل من يعرف لما ينزل عرض جديد.',

  txtEnterTheCodeSentToThisEmail: 'أدخل رمز البريد الإلكتروني الذي أرسل إلى ',

  lblLoginWelcome: ' تسجيل الدخول ',
  lblOffers: 'العروض',
  lblStores: 'المتاجر',
  lblNoOffers: 'لا توجد عروض',
  lblNoStores: 'لا توجد متاجر',
  lblMostPopularOffers: 'الأكثر شعبية',
  lblLatestOffers: 'الأحدث',
  lblOffersCount: 'عدد العروض',
  lblNoAccount: 'لا يوجد حساب',
  lblConfirmAccount: 'تأكيد الحساب',
  lblConfirmResetPassword: 'تأكيد إعادة تعيين كلمة المرور',
  lblFavorites: 'المفضلة',
  lbldarkMode: 'الوضع الليلي',
  lbllanguage: 'اللغة',
  lblContact: 'اتصل بنا',
  lblVersion: 'الإصدار',
  lblJoinAsMerchant: 'انضمام كتاجر',
  lblTapToLogin: 'انقر لتسجيل الدخول',
  lblGuest: 'زائر',
  lblcategory: 'الفئة',
  lblNearbyOffers: 'العروض القريبة',
  lblDiscoverNearby: 'اكتشف العروض القريبة',
  lblSearch: 'بحث',
  lblAdress: 'العنوان',
  lblExpiresOn: 'ينتهي في',
  lblYemeniRial: 'ر.ي',
  lblNoInternet: 'لا يوجد اتصال بالإنترنت',
  lblRefresh: 'إعادة المحاولة',
  lblNoInternetMessage:
      'لا يوجد اتصال بالإنترنت حالياً.\nيرجى التحقق من الاتصال والمحاولة مرة أخرى.',
  lblOOOps: 'عذراً!',
  lblPhone: 'الهاتف',
  lblFacebook: 'فيسبوك',
  lblInstagram: 'انستقرام',
  lblSnapchat: 'السناب',

  lblWelcome: 'مرحبا بك ',
  lblHome: 'الرئيسية',
  lblLogin: 'تسجيل الدخول',
  lblRegister: 'إنشاء حساب',
  lblLogout: 'تسجيل الخروج',
  lblForgotPassword: 'نسيت كلمة المرور',
  lblOrLoginWith: 'أو تسجيل الدخول بواسطة',
  lblDontHaveAccount: 'ليس لديك حساب؟',
  lblAlreadyHaveAccount: 'لديك حساب بالفعل؟',
  lblProfile: 'الملف الشخصي',
  lblSubjects: 'المواد',
  lblCourses: 'الدورات',
  lblMyCourses: 'دوراتي',
  lblArabicLang: 'العربية',
  lblEnglishLang: 'الإنجليزية',
  lblEnterYourDetails: 'أدخل تفاصيلك أدناه لإنشاء حسابك',
  lblPolicyPrivacy: 'بإنشاء حساب، فإنك توافق على شروطنا وأحكامنا.',
  lblVerifyEmail: 'تحقق من البريد الإلكتروني',
  lblCodeSentTo: 'تم إرسال الرمز إلى',
  lblDontRecieveCode: 'لم تستلم الرمز؟',
  lblResendCode: 'إعادة إرسال',
  lblResetPassword: 'إعادة تعيين كلمة المرور',
  lblNoSubjects: 'لا توجد مواد',
  lblNoCourses: 'لا توجد دورات',
  lblLearning: 'التعلم',
  lblNewCourse: 'دورة جديدة',
  lblEditCourse: 'تعديل الدورة',
  lblchooseCoursePhoto: 'اختر صورة الدورة',
  lblEditPhoto: 'تعديل الصورة',
  lblNoPhotoAvailable: 'لا تتوفر صورة',
  lblNoPhotoSelected: 'لم يتم اختيار صورة',
  lblDeleteCourse: 'حذف الدورة',
  lblAreYouSureYouWantToDeleteThisCourse:
      'هل أنت متأكد أنك تريد حذف هذه الدورة؟',
  lblError: 'خطأ',
  txtNoDescription: 'لا يوجد وصف',
  lblMerchantData: 'بيانات التاجر',
  lblStoreData: 'بيانات المتاجر',
  lblNotifications: 'الإشعارات',
  lblSearchByImage: 'بصورة',
  lblSearchByVector: ' نصي',
  lblAddStore: 'إضافة متجر',
  lblTapToUpload: 'انقر لتحميل',

  // hnt
  hntWebsite: 'الموقع الإلكتروني',
  hntAddress: 'العنوان',
  hntStoreName: 'اسم المتجر',
  hntStoreDescription: 'وصف المتجر',
  hntStoreCategory: 'الفئة المتجر',
  hntStorePhone: 'رقم الهاتف المتجر',
  hntStoreLogo: 'شعار المتجر',
  hntTakePhoto: 'التقط صورة',
  hntChoosePhoto: 'اختر صورة',

  hntOtp: 'الرمز',
  hntGender: 'الجنس',
  hntSearch: 'بحث',
  hntEmail: 'البريد الإلكتروني',
  hntPassword: 'كلمة المرور',
  hntConfirmPassword: 'تأكيد كلمة المرور',
  hntName: 'الاسم',
  hntRole: 'الدور',
  hntPhone: 'الهاتف',
  hntSelectSubject: 'اختر موضوع',
  hntPleaseSelectASubject: 'الرجاء اختيار موضوع',

  // btn
  btnNext: 'التالي',
  btnSkip: 'تخطي',
  btnLetsGo: 'إبدا',
  btnViewAll: 'عرض الكل',
  btnGoogleLogin: 'تسجيل الدخول بواسطة جوجل',
  btnGoogleRegister: 'تسجيل الدخول بواسطة جوجل',
  btnResendOtpEmail: 'إعادة إرسال رمز البريد الإلكتروني',
  btnConfirmAccount: 'تأكيد الحساب',
  btnDiscover: 'اكتشف',
  btnViewDetails: 'عرض التفاصيل',
  btnCall: 'اتصل',
  btnFilter: 'تصفية',
  btnNewOffer: ' عرض جديد',

  // Filter Button
  lblFilters: 'الفلاتر',
  lblCategoreStores: 'المتاجر',
  lblOfferTypes: 'فئه العروض',
  lblDateRange: 'تاريخ الانتهاء ',
  lblMinDate: 'من ',
  lblMaxDate: ' الئ',
  lblPriceRange: ' السعر بعد',
  lblMinPrice: 'السعر الأدنى',
  lblMaxPrice: 'السعر الأقصى',
  lblpercentage: 'النسبة (%)',
  lblMaxPercentage: 'اكبر من اويساوي',
  lblMinPercentage: 'اصغر من او يساوي',
  lblSelectCatogrey: 'اختر فئات',
  lblSelectStores: 'اختر متاجر',
  lblSelectOfferTypes: 'اختر نوع عروض',

  btnLogin: 'تسجيل الدخول',
  btnRegister: 'إنشاء حساب',
  btnLogout: 'تسجيل الخروج',
  btnForgotPassword: 'نسيت كلمة المرور',
  btnSend: 'إرسال',
  btnSubmit: 'تقديم',
  btnVerify: 'تحقق',
  btnCancel: 'إلغاء',
  btnDelete: 'حذف',
  btnAdd: 'إضافة',
  btnUpdate: 'تحديث',
  btnYes: 'نعم',
  btnNo: 'لا',

  // validated messages
  msgEmailRequired: 'البريد الإلكتروني مطلوب',
  msgPasswordRequired: 'كلمة المرور مطلوبة',
  msgConfirmPasswordRequired: 'تأكيد كلمة المرور مطلوبة',
  msgNameRequired: 'الاسم مطلوب',
  msgPhoneRequired: 'الهاتف مطلوب',
  msgEmailInvalid: 'البريد الإلكتروني غير صحيح',
  msgPasswordInvalid: 'كلمة المرور غير صحيحة',
  msgConfirmPasswordInvalid: 'تأكيد كلمة المرور غير صحيحة',
  msgNameInvalid: 'الاسم غير صحيح',
  msgPhoneInvalid: 'الهاتف غير صحيح',
  msgPasswordsDoNotMatch: 'كلمتا المرور غير متطابقتين',
  msgEmailAlreadyExists: 'البريد الإلكتروني مسجل بالفعل',
  msgInvalidOtp: 'رمز غير صحيح',
  msgThisFieldIsRequired: 'هذا الحقل مطلوب',
  msgUrlInvalid: 'الرابط غير صحيح',
  msgUrlShouldContain: 'الرابط يجب أن يحتوي على ',
  msgUrlShouldContainFacebook: 'الرابط يجب أن يحتوي على facebook.com',
  msgUrlShouldContainInstagram: 'الرابط يجب أن يحتوي على instagram.com',
  msgUrlShouldContainSnapchat: 'الرابط يجب أن يحتوي على snapchat.com',

  // offer hints
  hntOfferTitle: 'عنوان العرض',
  hntOfferDescription: 'وصف العرض',
  hntOfferCategory: 'الفئة العرض',
  hntOfferImage: 'صورة العرض',
  hntOfferPriceBefore: 'السعر قبل الخصم',
  hntOfferPriceAfter: 'السعر بعد الخصم',
  hntOfferStartDate: 'تاريخ البدء',
  hntOfferEndDate: 'تاريخ الانتهاء',

  btnAddOffer: 'إضافة العرض',
  btnUpdateOffer: 'تحديث العرض',
};
